services:
  - type: web
    name: smartparking-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: smartparking_secret_key
      - key: NODE_ENV
        value: production
